package org.lembeck.fs.simconnect.constants;

public enum ExceptionType {

    SIMCONNECT_EXCEPTION_NONE,
    SIMCONNECT_EXCEPTION_ERROR,
    SIMCONNECT_EXCEPTION_SIZE_MISMATCH,
    SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID,
    SIMCONNECT_EXCEPTION_UNOPENED,
    SIMCONNECT_EXCEPTION_VERSION_MISMATCH,
    SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS,
    SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED,
    SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES,
    SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE,
    SIMCONNECT_EXCEPTION_TOO_MANY_MAPS,
    SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS,
    SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS,
    SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT,
    SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR,
    SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION,
    SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION,
    SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION,
    SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE,
    SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE,
    SIMCONNECT_EXCEPTION_DATA_ERROR,
    SIMCONNECT_EXCEPTION_INVALID_ARRAY,
    SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED,
    SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED,
    SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE,
    SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION,
    SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED,
    SIMCONNECT_EXCEPTION_INVALID_ENUM,
    SIMCONNECT_EXCEPTION_DEFINITION_ERROR,
    SIMCONNECT_EXCEPTION_DUPLICATE_ID,
    SIMCONNECT_EXCEPTION_DATUM_ID,
    SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS,
    SIMCONNECT_EXCEPTION_ALREADY_CREATED,
    SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE,
    SIMCONNECT_EXCEPTION_OBJECT_CONTAINER,
    SIMCONNECT_EXCEPTION_OBJECT_AI,
    SIMCONNECT_EXCEPTION_OBJECT_ATC,
    SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE,
    SIMCONNECT_EXCEPTION_JETWAY_DATA,
    SIMCONNECT_EXCEPTION_ACTION_NOT_FOUND,
    SIMCONNECT_EXCEPTION_NOT_AN_ACTION,
    SIMCONNECT_EXCEPTION_INCORRECT_ACTION_PARAMS,
    SIMCONNECT_EXCEPTION_GET_INPUT_EVENT_FAILED,
    SIMCONNECT_EXCEPTION_SET_INPUT_EVENT_FAILED,
    UNKNOWN;

    public static ExceptionType ofId(int id) {
        return switch (id) {
            case 0 -> SIMCONNECT_EXCEPTION_NONE;
            case 1 -> SIMCONNECT_EXCEPTION_ERROR;
            case 2 -> SIMCONNECT_EXCEPTION_SIZE_MISMATCH;
            case 3 -> SIMCONNECT_EXCEPTION_UNRECOGNIZED_ID;
            case 4 -> SIMCONNECT_EXCEPTION_UNOPENED;
            case 5 -> SIMCONNECT_EXCEPTION_VERSION_MISMATCH;
            case 6 -> SIMCONNECT_EXCEPTION_TOO_MANY_GROUPS;
            case 7 -> SIMCONNECT_EXCEPTION_NAME_UNRECOGNIZED;
            case 8 -> SIMCONNECT_EXCEPTION_TOO_MANY_EVENT_NAMES;
            case 9 -> SIMCONNECT_EXCEPTION_EVENT_ID_DUPLICATE;
            case 10 -> SIMCONNECT_EXCEPTION_TOO_MANY_MAPS;
            case 11 -> SIMCONNECT_EXCEPTION_TOO_MANY_OBJECTS;
            case 12 -> SIMCONNECT_EXCEPTION_TOO_MANY_REQUESTS;
            case 13 -> SIMCONNECT_EXCEPTION_WEATHER_INVALID_PORT;
            case 14 -> SIMCONNECT_EXCEPTION_WEATHER_INVALID_METAR;
            case 15 -> SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_GET_OBSERVATION;
            case 16 -> SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_CREATE_STATION;
            case 17 -> SIMCONNECT_EXCEPTION_WEATHER_UNABLE_TO_REMOVE_STATION;
            case 18 -> SIMCONNECT_EXCEPTION_INVALID_DATA_TYPE;
            case 19 -> SIMCONNECT_EXCEPTION_INVALID_DATA_SIZE;
            case 20 -> SIMCONNECT_EXCEPTION_DATA_ERROR;
            case 21 -> SIMCONNECT_EXCEPTION_INVALID_ARRAY;
            case 22 -> SIMCONNECT_EXCEPTION_CREATE_OBJECT_FAILED;
            case 23 -> SIMCONNECT_EXCEPTION_LOAD_FLIGHTPLAN_FAILED;
            case 24 -> SIMCONNECT_EXCEPTION_OPERATION_INVALID_FOR_OBJECT_TYPE;
            case 25 -> SIMCONNECT_EXCEPTION_ILLEGAL_OPERATION;
            case 26 -> SIMCONNECT_EXCEPTION_ALREADY_SUBSCRIBED;
            case 27 -> SIMCONNECT_EXCEPTION_INVALID_ENUM;
            case 28 -> SIMCONNECT_EXCEPTION_DEFINITION_ERROR;
            case 29 -> SIMCONNECT_EXCEPTION_DUPLICATE_ID;
            case 30 -> SIMCONNECT_EXCEPTION_DATUM_ID;
            case 31 -> SIMCONNECT_EXCEPTION_OUT_OF_BOUNDS;
            case 32 -> SIMCONNECT_EXCEPTION_ALREADY_CREATED;
            case 33 -> SIMCONNECT_EXCEPTION_OBJECT_OUTSIDE_REALITY_BUBBLE;
            case 34 -> SIMCONNECT_EXCEPTION_OBJECT_CONTAINER;
            case 35 -> SIMCONNECT_EXCEPTION_OBJECT_AI;
            case 36 -> SIMCONNECT_EXCEPTION_OBJECT_ATC;
            case 37 -> SIMCONNECT_EXCEPTION_OBJECT_SCHEDULE;
            case 38 -> SIMCONNECT_EXCEPTION_JETWAY_DATA;
            case 39 -> SIMCONNECT_EXCEPTION_ACTION_NOT_FOUND;
            case 40 -> SIMCONNECT_EXCEPTION_NOT_AN_ACTION;
            case 41 -> SIMCONNECT_EXCEPTION_INCORRECT_ACTION_PARAMS;
            case 42 -> SIMCONNECT_EXCEPTION_GET_INPUT_EVENT_FAILED;
            case 43 -> SIMCONNECT_EXCEPTION_SET_INPUT_EVENT_FAILED;
            default -> UNKNOWN;
        };
    }
}